steps:
# Build the Docker image for the web crawler
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/steal-house-crawler:$COMMIT_SHA', '.']

# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/steal-house-crawler:$COMMIT_SHA']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy steal-house-crawler \
      --image gcr.io/$PROJECT_ID/steal-house-crawler:$COMMIT_SHA \
      --platform managed \
      --region europe-west4 \
      --memory 2Gi \
      --cpu 1 \
      --timeout 3600 \
      --service-account steal-house-crawler@$PROJECT_ID.iam.gserviceaccount.com \
      --no-allow-unauthenticated \
      --max-instances 1 \
      --set-secrets=POSTGRES_USER=projects/$PROJECT_ID/secrets/POSTGRES_USER:latest,POSTGRES_PASSWORD=projects/$PROJECT_ID/secrets/POSTGRES_PASSWORD:latest,POSTGRES_DB=projects/$PROJECT_ID/secrets/POSTGRES_DB:latest,POSTGRES_HOST=projects/$PROJECT_ID/secrets/POSTGRES_HOST:latest,DEEPSEEK_API_KEY=projects/$PROJECT_ID/secrets/DEEPSEEK_API_KEY:latest,GOOGLE_API_KEY=projects/$PROJECT_ID/secrets/GOOGLE_API_KEY:latest,VESTEDA_EMAIL=projects/$PROJECT_ID/secrets/VESTEDA_EMAIL:latest,VESTEDA_PASSWORD=projects/$PROJECT_ID/secrets/VESTEDA_PASSWORD:latest

images:
- 'gcr.io/$PROJECT_ID/steal-house-crawler:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY 