name: stealhouse

services:
  db:
    image: postgres:latest
    container_name: stealhouse-db
    env_file:
      - ../../.env_docker
    ports:
      - "${POSTGRES_PORT:?error}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crawler:
    container_name: stealhouse-crawler
    build:
      context: ../../
      dockerfile: ./scripts/docker/Dockerfile
    depends_on:
      - db
    env_file:
      - ../../.env_docker
    environment:
      POSTGRES_HOST: db

volumes:
  postgres_data:
