name: stealhouse

services:
  db:
    image: postgres:latest
    container_name: stealhouse-db
    env_file:
      - ../../.env_docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  crawler:
    container_name: stealhouse-crawler
    build:
      context: ../../
      dockerfile: ./scripts/docker/Dockerfile
    depends_on:
      - db
    env_file:
      - ../../.env_docker
    environment:
      POSTGRES_HOST: db

volumes:
  postgres_data:
