"""add is_parkingspot to houses

Revision ID: 6a0f80e2cff5
Revises: ea75e2c76bc8
Create Date: 2025-05-10 17:10:14.039634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a0f80e2cff5"
down_revision: Union[str, None] = "ea75e2c76bc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "houses",
        sa.Column(
            "is_parkingspot",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
        schema="steal_house",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("houses", "is_parkingspot", schema="steal_house")
    # ### end Alembic commands ###
