"""Create house tables in steal_house schema

Revision ID: 036802456a1e
Revises: 0eef56be1e4c
Create Date: 2025-03-20 00:01:26.449894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036802456a1e'
down_revision: Union[str, None] = '0eef56be1e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('high_demand', sa.Boolean(), nullable=True),
    sa.Column('demand_message', sa.String(), nullable=True),
    sa.Column('detail_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='steal_house'
    )
    op.create_table('detail_houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('rental_price', sa.String(), nullable=False),
    sa.Column('service_costs', sa.String(), nullable=True),
    sa.Column('min_income_single', sa.String(), nullable=True),
    sa.Column('min_income_joint', sa.String(), nullable=True),
    sa.Column('read_more_url', sa.String(), nullable=True),
    sa.Column('square_meters', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('energy_label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('available_from', sa.String(), nullable=True),
    sa.Column('complex', sa.String(), nullable=True),
    sa.Column('complex_name', sa.String(), nullable=True),
    sa.Column('complex_description', sa.Text(), nullable=True),
    sa.Column('year_of_construction', sa.Integer(), nullable=True),
    sa.Column('number_of_objects', sa.String(), nullable=True),
    sa.Column('number_of_floors', sa.String(), nullable=True),
    sa.Column('complex_image_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_map_url', sa.String(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['steal_house.gallery_houses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='steal_house'
    )
    op.create_table('floor_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['steal_house.detail_houses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='steal_house'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('floor_plans', schema='steal_house')
    op.drop_table('detail_houses', schema='steal_house')
    op.drop_table('gallery_houses', schema='steal_house')
    # ### end Alembic commands ###
