"""Add request_viewing_url to detail_houses

Revision ID: 730732ab93c4
Revises: 036802456a1e
Create Date: 2025-03-20 17:37:12.756715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730732ab93c4'
down_revision: Union[str, None] = '036802456a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_houses', sa.Column('request_viewing_url', sa.String(), nullable=True), schema='steal_house')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail_houses', 'request_viewing_url', schema='steal_house')
    # ### end Alembic commands ###
